<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="icon" type="image/png" href="{{ asset('images/logosapa.png') }}"><title>Dashboard Petugas | SAPA</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="dashboard-page">
<header class="dashboard-header"><a class="brand" href="{{ url('/') }}"><img class="brand-logo" src="{{ asset('images/logosapa.png') }}" alt="SAPA - Sistem Aspirasi dan Pengaduan Masyarakat"></a><div class="dashboard-header-actions"><span class="header-role"><i></i> Petugas aktif</span><span class="header-name">{{ auth()->user()->name }}</span><form method="POST" action="{{ route('staff.logout') }}">@csrf<button class="text-button" type="submit">Keluar</button></form></div></header>
<main class="dashboard-shell">
<div class="dashboard-heading"><div><p class="eyebrow">RUANG KERJA PETUGAS</p><h1>Ringkasan laporan</h1><p class="form-intro">Pantau laporan warga dan lakukan tindak lanjut dari satu tempat.</p></div><div class="dashboard-date">{{ now()->translatedFormat('l, d F Y') }}</div></div>
<div class="dashboard-stats"><div class="stat-card"><span class="stat-icon stat-icon-green">&#128196;</span><div><small>Total laporan</small><strong>{{ $reports->total() }}</strong></div></div><div class="stat-card"><span class="stat-icon stat-icon-orange">&#9679;</span><div><small>Laporan baru</small><strong>{{ $statusCounts->get('baru', 0) }}</strong></div></div><div class="stat-card"><span class="stat-icon stat-icon-blue">&#8635;</span><div><small>Sedang diproses</small><strong>{{ $statusCounts->get('diproses', 0) }}</strong></div></div><div class="stat-card"><span class="stat-icon stat-icon-purple">&#10003;</span><div><small>Selesai</small><strong>{{ $statusCounts->get('selesai', 0) }}</strong></div></div></div>
@if (session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="report-toolbar"><div><h2>Laporan masuk</h2><span>{{ $reports->total() }} laporan{{ $activeStatus !== 'semua' ? ' dengan status ' . $activeStatus : '' }}</span></div><form class="status-filter" method="GET" action="{{ route('staff.dashboard') }}"><label for="status-filter">Tampilkan</label><select id="status-filter" name="status" onchange="this.form.submit()"><option value="semua" @selected($activeStatus === 'semua')>Semua laporan</option><option value="baru" @selected($activeStatus === 'baru')>Baru ({{ $statusCounts->get('baru', 0) }})</option><option value="diproses" @selected($activeStatus === 'diproses')>Diproses ({{ $statusCounts->get('diproses', 0) }})</option><option value="selesai" @selected($activeStatus === 'selesai')>Selesai ({{ $statusCounts->get('selesai', 0) }})</option><option value="ditolak" @selected($activeStatus === 'ditolak')>Ditolak ({{ $statusCounts->get('ditolak', 0) }})</option></select></form></div>
<div class="report-list">@forelse ($reports as $report)<article class="report-item"><div class="report-content"><div class="report-meta"><span class="status status-{{ $report->status }}">{{ ucfirst($report->status) }}</span><span>{{ $report->created_at->format('d M Y, H:i') }}</span><span class="tracking-code">{{ $report->tracking_code }}</span></div><h2>{{ $report->title }}</h2><p class="report-category">{{ $report->category }} <b>&middot;</b> {{ $report->location }}</p><p>{{ $report->description }}</p>@if ($report->citizen_name || $report->citizen_phone || $report->citizen_email)<p class="report-contact">Pelapor: {{ $report->citizen_name ?: 'Anonim' }} &middot; Telp: {{ $report->citizen_phone }} @if ($report->citizen_email) &middot; {{ $report->citizen_email }} @endif</p>@endif @if ($report->photo_path)<a class="report-photo" target="_blank" href="{{ route('staff.reports.photo', $report) }}"><img src="{{ route('staff.reports.photo', $report) }}" alt="Foto pendukung laporan {{ $report->tracking_code }}"><span>Lihat foto penuh <b>&rarr;</b></span></a>@else <span class="no-photo">Tidak ada foto pendukung</span>@endif</div><form class="follow-up-form" method="POST" action="{{ route('staff.reports.update', $report) }}">@csrf @method('PATCH')<div class="follow-up-title"><span>&#9998;</span><strong>Tindak lanjut</strong></div><label>Status<select name="status"><option value="baru" @selected($report->status === 'baru')>Baru</option><option value="diproses" @selected($report->status === 'diproses')>Diproses</option><option value="selesai" @selected($report->status === 'selesai')>Selesai</option><option value="ditolak" @selected($report->status === 'ditolak')>Ditolak</option></select></label><label>Catatan petugas<textarea name="staff_note" rows="4" placeholder="Tulis perkembangan laporan">{{ $report->staff_note }}</textarea></label><button class="button button-primary" type="submit">Simpan perubahan <span>&rarr;</span></button></form></article>@empty<div class="empty-state"><strong>Tidak ada laporan pada filter ini.</strong><span>Coba pilih status laporan yang lain.</span></div>@endforelse</div>{{ $reports->links() }}</main>
</body>
</html>
